name: Build all samples
on: [push, pull_request]
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: 'Build all samples using JShell'
        run: jshell build-all-samples.jsh
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2.12.0
        if: always()
        with:
          junit_files: "**/build/test-results/*test/*.xml"
